AWSTemplateFormatVersion: '2010-09-09'
Description: 'NAT Gateway Stack - Creates Elastic IP and NAT Gateway'

Parameters:
  PublicSubnetId:
    Type: String
    Description: Public Subnet ID where NAT Gateway will be placed

Resources:
  # Elastic IP for NAT Gateway
  NATElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: NAT Gateway EIP

  # NAT Gateway
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATElasticIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: NAT Gateway

Outputs:
  NATGatewayId:
    Description: NAT Gateway ID
    Value: !Ref NATGateway
    Export:
      Name: !Sub '${AWS::StackName}-NATGatewayId'
  
  NATElasticIPAddress:
    Description: Elastic IP address of NAT Gateway
    Value: !Ref NATElasticIP
    Export:
      Name: !Sub '${AWS::StackName}-NATElasticIP'
