AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main Stack - Orchestrates all nested stacks for AWS Infrastructure'

Parameters:
  VpcCIDR:
    Type: String
    Default: '10.0.0.0/16'
    Description: CIDR block for VPC
  
  PublicSubnetCIDR:
    Type: String
    Default: '10.0.1.0/24'
    Description: CIDR block for Public Subnet
  
  PrivateSubnetCIDR:
    Type: String
    Default: '10.0.2.0/24'
    Description: CIDR block for Private Subnet
  
  AvailabilityZone:
    Type: String
    Default: 'us-east-1a'
    Description: Availability Zone for subnets
  
  AllowedIP:
    Type: String
    Default: '112.197.32.245/32'
    Description: IP address allowed to SSH into Public EC2
  
  AMIId:
    Type: String
    Default: 'ami-0866a3c8686eaeeba'
    Description: AMI ID for Ubuntu 24.04 LTS
  
  InstanceType:
    Type: String
    Default: 't2.micro'
    Description: EC2 Instance Type
  
  KeyName:
    Type: String
    Default: 'mykey'
    Description: Name of EC2 Key Pair
  
  NestedStacksS3Bucket:
    Type: String
    Description: S3 bucket name where nested stack templates are stored
  
  NestedStacksS3KeyPrefix:
    Type: String
    Default: 'cloudformation/nested-stacks/'
    Description: S3 key prefix for nested stack templates

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${NestedStacksS3Bucket}.s3.amazonaws.com/${NestedStacksS3KeyPrefix}vpc-stack.yaml'
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnetCIDR: !Ref PublicSubnetCIDR
        PrivateSubnetCIDR: !Ref PrivateSubnetCIDR
        AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: VPC-Stack

  # NAT Gateway Stack
  NATStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://${NestedStacksS3Bucket}.s3.amazonaws.com/${NestedStacksS3KeyPrefix}nat-stack.yaml'
      Parameters:
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
      Tags:
        - Key: Name
          Value: NAT-Stack

  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://${NestedStacksS3Bucket}.s3.amazonaws.com/${NestedStacksS3KeyPrefix}security-groups-stack.yaml'
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        AllowedIP: !Ref AllowedIP
      Tags:
        - Key: Name
          Value: SecurityGroups-Stack

  # Route Tables Stack
  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - NATStack
    Properties:
      TemplateURL: !Sub 'https://${NestedStacksS3Bucket}.s3.amazonaws.com/${NestedStacksS3KeyPrefix}route-tables-stack.yaml'
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
        NATGatewayId: !GetAtt NATStack.Outputs.NATGatewayId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
      Tags:
        - Key: Name
          Value: RouteTables-Stack

  # EC2 Stack
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
      - RouteTablesStack
    Properties:
      TemplateURL: !Sub 'https://${NestedStacksS3Bucket}.s3.amazonaws.com/${NestedStacksS3KeyPrefix}ec2-stack.yaml'
      Parameters:
        AMIId: !Ref AMIId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        PublicSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.PublicSecurityGroupId
        PrivateSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.PrivateSecurityGroupId
      Tags:
        - Key: Name
          Value: EC2-Stack

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCId
  
  PublicSubnetId:
    Description: Public Subnet ID
    Value: !GetAtt VPCStack.Outputs.PublicSubnetId
  
  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnetId
  
  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !GetAtt VPCStack.Outputs.InternetGatewayId
  
  NATGatewayId:
    Description: NAT Gateway ID
    Value: !GetAtt NATStack.Outputs.NATGatewayId
  
  PublicSecurityGroupId:
    Description: Public Security Group ID
    Value: !GetAtt SecurityGroupsStack.Outputs.PublicSecurityGroupId
  
  PrivateSecurityGroupId:
    Description: Private Security Group ID
    Value: !GetAtt SecurityGroupsStack.Outputs.PrivateSecurityGroupId
  
  PublicRouteTableId:
    Description: Public Route Table ID
    Value: !GetAtt RouteTablesStack.Outputs.PublicRouteTableId
  
  PrivateRouteTableId:
    Description: Private Route Table ID
    Value: !GetAtt RouteTablesStack.Outputs.PrivateRouteTableId
  
  PublicInstanceId:
    Description: Public EC2 Instance ID
    Value: !GetAtt EC2Stack.Outputs.PublicInstanceId
  
  PublicInstancePublicIP:
    Description: Public EC2 Instance Public IP
    Value: !GetAtt EC2Stack.Outputs.PublicInstancePublicIP
  
  PrivateInstanceId:
    Description: Private EC2 Instance ID
    Value: !GetAtt EC2Stack.Outputs.PrivateInstanceId
  
  PrivateInstancePrivateIP:
    Description: Private EC2 Instance Private IP
    Value: !GetAtt EC2Stack.Outputs.PrivateInstancePrivateIP
